name: Docker Init for Python

on:
  push:
    branches:
      - main

jobs:
  docker-init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Verify main.py exists
        run: |
          if [ ! -f "main.py" ]; then
            echo "Error: main.py not found!"
            exit 1
          fi

      - name: Run docker init for Python
        run: |
          echo -e "1\n1\n3.9\n./app\npython main.py\n" | docker init

      - name: Build Docker image
        run: docker build -t my-python-app .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker tag my-python-app my-dockerhub-username/my-python-app:latest
          docker push my-dockerhub-username/my-python-app:latest
